title: "RP's Den"
subtitle: // a personal website
email: rahul.peter@gmail.com
description: "This is Rahul's personal site. Musician, programmer and producer."
# domain: blog.mauromotion.com
url: www.rp335orb.com
twitter_username: BleuOrbOfficial
github_username: RP335
logo: "/assets/images/rp_logo.jpg"
github: [metadata]

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mauro" # "air"contrast", "aqua", "dirt", "sunrise", "dark", "default", "neon", "plum", "mint"
search: true

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name: "Rahul Peter"
  avatar: "assets/images/pfp.jpg"
  bio: "ouwee"
  location: "Blr"
  # email:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:rahul.peter@gmail.com"
    - label: "GitHub"
      icon: "fa-brands fa-square-github"
      url: "https://github.com/RP335"
    - label: "SoundCloud"
      icon: "fa-brands fa-soundcloud"
      url: "https://soundcloud.com/gr8beatz-320169455"
    - label: "YouTube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@bleuorb"
    - label: "Spotify"
      icon: "fa-brands fa-spotify"
      url: "https://open.spotify.com/artist/3gig754purvj3njLtEW8JH?si=oFbczxjVQSKth3UiA_g55A"
    - label: "Twitter"
      icon: "fa-brands fa-twitter"
      url: "https://twitter.com/BleuOrbOfficial"
    - label: "Facebook"
      icon: "fa-brands fa-facebook"
      url: "https://facebook.com/rahul.peter.39"
    - label: "Gumroad"
      icon: "fa-brands fa-gumroad"
      url: "https://bleuorb.gumroad.com/"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/rahul-peter-172293194/"



include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
  # _now_archive
  - scope:
      path: ""
      type: now
    values:
      layout: single
      author_profile: false
      share: true
      show_date: false

# Collections
collections:
  now:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/

footer:
  links:
    # - label: "Mastodon"
    #   icon: "fab fa-mastodon"
    #   url: "https://mograph.social/@mauro"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
